config/routes.rb
  collection do
   get  'platform'
   get 'bank_info'
 end

 member do
  get 'paid'
end
end

mount WeixinRailsMiddleware::Engine, at: "/"

root :to=>"home#index",:constraints=>{ :subdomain=>/^(www)?$/ }
get 'blank'=>"home#blank"
get 'home'=>"home#index"

resources :pages, :only=>[:show]

namespace :auth do
  resources :accounts
  resources :weixin do
    get 'callback',:on=>:member
  end
  resources :weibo do
    get 'callback',:on=>:collection
  end
  resources :douban do
    get 'callback',:on=>:collection
  end
end

resources :sessions

get 'register'=>'users#new'
resources :users do
  get 'forgot_password', :on=>:collection
  post 'send_reset_password_instruction', :on=>:collection    
  get 'reset_password',:on=>:collection
  post 'search', :on=>:collection
  post 'change_password',:on=>:collection
  post 'update' ,:on=>:member
end

resources :vshop do
  collection do
    get 'login'
    get 'register'
    get 'article'
    get 'apply'
    post 'search'
    post 'change_password'
    get 'goods'
    get 'orders'
    get 'members'
    get 'weixin'
    post "destory"
  end
  member do
    get :user
    get :category
    get :commodity
    get :order
     get :payments
     get :native
     post :paynotifyurl
     get :paynotifyurl
     get :feedback
   end
 end

 get 'auto_login'=>"sessions#auto_login"
 get 'login'=>"sessions#login"
 get 'mlogin'=>"sessions#new_mobile"
 get 'mregister'=>"sessions#register_mobile"
 post 'login'=>"sessions#create"
 post 'mlogin'=>"sessions#create"
 get 'logout'=>"sessions#destroy"
 get 'topmenu'=>"home#topmenu"

 scope :module=> "events" do
  resources :user_survey, :controller=>"survey" do
    post "add_mobile", :on=>:collection
  end
end

namespace :events do
  resources :applicants
end

resources :events

scope :module => "blog" do
    root :to => "articles#index"
    resources :articles

  end

  scope :module => "magazine" do
    resources :topics do
      resources :pages
    end
    match '/more_topics' => 'topics#more'
    match '/list_topics' => 'topics#list'
    match '/flash' => 'flashes#index'
  end

  scope :module => "memberships" do
    match '/vip' => 'vip#index'
    resource  :card do
      collection do
        get 'search'

        get 'activation'
        post 'confirm_activation'
        post 'validate_activation'
        post 'activate'
        get 'complete_activation'
        post 'input_mobile'
        post 'select'
        put 'update_mobile'
        put 'modify_mobile'
        get 'cancel_mobile'

        get 'purchase'
        scope "purchase" do
          post 'confirm_buyer'
          post 'confirm_user'
          get 'user'
        end

        get 'send_sms_code'

      end
    end
    resources  :member_cards
  end

  get 'admin'=>'admin/sessions#new'

  namespace :admin do

    get 'logout'=>'sessions#destroy'
    resources :tracks do
      get :pages,:on=>:collection
    end

    resources :discount_codes

    resources :carts do

    end
    resources :wechat do
      get :menu,:on=>:collection
      get :menu_edit,:on=>:collection
      get :followers, :on=>:collection
      get :followers_import, :on=>:collection
      get :follower_renew,:on=> :collection
      get :groups, :on=>:collection
      get :batch_sending, :on=>:collection
      get :weixin,:on=>:collection
    end
    resources :resources
    resources :permissions do
    end
    get 'permissions/:id/role' => 'permissions#role', as: :permission_role

    resources :suppliers do
      get 'update_state',:on=>:collection
    end

    resources :sessions
    resources :coupons
    resources :goods_cats do
      get :create_top,:on=>:collection
      get :toggle_future,:on=>:member
      get :toggle_agent,:on=>:member
      get :toggle_sell,:on=>:member
      post :save_top,:on=>:collection
    end
    resources :goods_types do
      put :updateType,:on=>:member
    end
    resources :goods_labels do
      put :updateLabel,:on=>:member
      get :createLabel,:on=>:collection
    end

    resources :brand_adms do
      get :delete
      put :update_brand,:on=>:member
    end

    resources :goods do
      post "export", :on=>:collection
      post "import", :on=>:collection
      post "remove_spec_item",:on=>:member
      get "add_spec_item",:on=>:member
      get "spec",:on=>:member
      put "update_spec",:on=>:member
      get 'select_goods',:on=>:collection
      get 'collocation',:on=>:member
      get 'set_suits',:on=>:member
      get 'cancel_suits',:on=>:member
      post 'create_collocation',:on=>:collection
      get 'search', :on=>:collection
      get 'select_gifts',:on=>:collection
      put 'batch',:on=>:collection
      get 'select_all',:on=>:collection

      get :toggle_future,:on=>:member
      get :toggle_agent,:on=>:member
      get :toggle_sell,:on=>:member
    end
    resources :spec_items

    resources :images do
      post "mark", :on=>:collection
      post "rollback",:on=>:collection
      post "refresh",:on=>:collection
    end
    resources :articles do
      post 'set_position',:on=>:collection
    end
    resources :topics do
      post 'set_position',:on=>:collection
      post 'published_at',:on=>:member
    end
    resources :pages

    resources :members do
      post "export",:on=>:collection
      post "column_reload",:on=>:collection
      post "send_sms",:on=>:collection
      post "send_sms2",:on=>:collection
      get :info,:on=>:member
      put :updateInfo,:on=>:member
    end

    resources :cards do
      get 'buy',:on=>:member
      get 'use',:on=>:member
      get 'edit_user',:on=>:member
      get 'edit_pay',:on=>:member
      get 'logs', :on=>:member
      post 'import', :on=>:collection
      post "export",:on=>:collection
      get "tag",:on=>:collection
      put "untag",:on=>:member
      put "cancel_order",:on=>:member
    end

    resources :users do
      get 'search',:on=>:collection
      post 'newuser',:on=>:collection
      put 'send_sms_code',:on=>:member
      put 'buy_card',:on=>:member
      put 'use_card',:on=>:collection
      get 'select', :on=>:member
      put 'validate_mobile',:on=>:member
    end
    resources :member_cards

    resources :tag_exts

    resources :configs

    resources :labels

    resources :emails do
      get 'send_all',:on=>:collection
    end

    resources :categories

    resources :applicants

    resources :events do
      get 'applicants',:on=>:member
    end

    resources :homes

    resources :brand_pages do
      get 'toggle', :on=>:member
      put 'order', :on=>:member
      put 'reco', :on=>:member
    end

    resources :promotions

    resources :new_coupons do
      get 'download', :on=>:member
      get  'select_coupons', :on=>:collection
    end

    resources :user_coupons

    resources :orders do
      collection do
        get 'search'
        post :export
        put 'batch'
      end

      member do
        get 'detail'
        get 'pay'
        post 'dopay'
        get 'delivery'
        post 'dodelivery'
        get 'print_order'
        get 'print_preparer'
        get 'reship'
        post 'doreship'
        get 'refund'
        post 'dorefund'
        get :comment
        put :update_memo
      end
    end

    resources :static_pages
    resources :footers

    resources :metas

    resources :specifications

    resources :tags

    resources :offline_coupons do
      get 'downloads',:on=>:member
    end

    resources :virtual_goods do
      post 'import', :on=>:collection
    end

    resources :payment_logs

  end
  get 'm' =>"mobile#show", :as=>"mobile" ,:controller=>"mobile"

  scope :module => "store" do

    get 'search' => "search#index", :as=> :search
    get 'mproducts' =>"goods#mproduct", :as=>"goods" ,:controller=>"goods"

    resources :products, :as=>"goods", :controller=>"goods" do
      get 'newest',:on=>:collection
      put 'fav',:on=>:member
      put 'unfav',:on=>:member
      get 'price',:on=>:member
      get 'more',:on=>:collection
      get 'suits', :on=>:collection
      get 'more_suits', :on=>:collection

    end

    resources :suppliers

    resources :coupons, :controller=>"offline_coupons" do
      post 'download',:on=>:member
    end

    resources :vgoods, :controller=>"virtual_goods",:only=>[:index,:show]
    post 'cart/add'=>"cart#add",:as=>:add_to_cart

    resources :cart do
      get 'manco_express'  ,:on=>:collection
      get 'distribution_manco',:on=>:collection
      post 'add',:on=>:collection
      get 'mobile', :on=>:collection
    end
    resources :brands,:only=>[:index,:show]
    resources :users
    resources :vshop
    resources :country, :as=>"countries", :controller=>"countries"
    resources :gallery, :as=>"cats", :controller=>"cats"

    get 'mgallery' =>"cats#show_mobile", :as=>"cats",:controller=>"cats"
    get 'mgoods_list'=>"cats#goods_list" ,:as=>"cats", :controller=>"cats"
    resources :goods,  :as=>"orders", :controller=>"orders" do
      member do
        get :goods
      end
    end

    get 'share' =>"orders#share"

    resources :orders, :except=>[:index] do
      member do
        get 'to_inventory'
        get 'out_inventory'
        post :pay
        get :detail
        get :goods

      end

      collection do
        post 'destroyaddr'
        get 'check_coupon'
        get  'new_mobile'
        get  'new_tairyo'

        post 'new_manco'
        get 'new_mobile_addr'
        get 'new_manco_addr'
        get 'departure'
        post 'arrival'
        get 'arrival'
        get 'mobile_show_order'
        get 'index_mobile'
        get 'share_order'   ###推荐订单
        get 'mobile_show'
        get 'addr_detail'
        get 'new_mobile_addr'
        post 'edit_addr'
        post 'xiugai_addr'
      end
    end

    resources :payments do

      collection do
        get 'callback'
        get 'debug'
        get 'pay'
        match ':adapter/notify'=>"payments#notify", :as=>"notify"
        match ':adapter/callback'=>"payments#callback", :as=>"callback"
      end

    end
  end

app/models/imodec/permission.rb
class Imodec::Permission < ActiveRecord::Base
  attr_accessible :manager_id, :rights
  
end

app/controllers/admin/permissions_controller.rb
#encoding:utf-8
class Admin::PermissionsController < Admin::BaseController
  def index
    @managers = Ecstore::Manager.all
  end

  def new
  end

  def update

    manager_id = params[:id]

    @permission = Imodec::Permission.where(:manager_id=>manager_id).first
    if @permission
      @permission.update_attributes(:rights=>params[:permission].to_json)
    else
      Imodec::Permission.create(:manager_id=>manager_id,:rights=>params[:permission].to_json)
    end
    
    redirect_to edit_admin_permission_path(params[:id]),:notice=>'权限保存成功!'
  end

  def edit
    @manager = Ecstore::Manager.find(params[:id])
    @resources = Imodec::Resource.where(:parent_id=>nil)
  end

  def destroy
    @manager = Ecstore::Manager.find(params[:id])
    @manager.account.user.destroy
    @manager.account.destroy
    @manager.destroy
    redirect_to admin_permissions_path
  end

  def role
    @managers = Ecstore::Manager.all
    @manager = Ecstore::Manager.find(params[:id])
    @method = :put
  end

 
end

app/helpers/admin/permissions_helper.rb
module Admin::PermissionsHelper
end

app/views/admin/permissions/_form.html.erb
<%= form_for :manager,:url=>newuser_admin_users_path, :method=>@method, :html => {:class => "form-horizontal"} do |f| %>
<%=f.hidden_field :app_id, :value=>"b2c"%>


<fieldset>
  <div class="control-group">
    <%= f.label :name, "用户名：", :class => "control-label" %>
    <div class="controls">
      <%=f.text_field :name%>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :email, "Email：", :class => "control-label" %>
    <div class="controls">
      <%=f.text_field :email%>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :mobile, "手机：", :class => "control-label" %>
    <div class="controls">
      <%=f.text_field :mobile%>
    </div>
  </div>

  <div class="control-group">
  <%= f.label :super, "角色：", :class => "control-label" %>
    <div class="controls">
      <%=f.select(:super, [['超级管理员', '0'], ['审核员', '2'], ['文章发布员', '3']]) %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :password, "密码：", :class => "control-label" %>
    <div class="controls">
      <%=f.password_field :password%>
    </div>
  </div>


  <div class="control-group">
    <div class="controls">
      <%= f.submit '确定', :class => "btn btn-primary" %>
      <%= link_to '返回', admin_tags_path,:class=>"btn" %>
    </div>
  </div>

</fieldset>
<% end %>

app/views/admin/permissions/destroy.html.erb
<h1>Admin::Permissions#destroy</h1>
<p>Find me in app/views/admin/permissions/destroy.html.erb</p>

app/views/admin/permissions/edit.html.erb
<div class="page-header">
    <h4>管理员 :
        <%=@manager.account.login_name%>
        (<%=@manager.super? ? "超级管理员" : @manager.name%>)
    </h4>
</div>
<%if @manager.super?%>
<div>哇，您是超级管理员哦,拥有所有权限!!!</div>
<%end%>
<%if flash[:notice]%>
<div class="alert"><%=flash[:notice]%></div>
<%end%>

<%=form_for :permission,:url=>admin_permission_path(@manager.user_id),:method=>:put do |f|%>
<div id="resources_tree">
    <div class="title">权限分配</div>
    <br>
    <% if current_admin.super? %>
    <% pcats = %w(goods order user article system) %>
    <% elsif %>
    <% pcats = ['article'] %>
    <% end %>
    <% pcats.each do |pcat|%>
    <ul>
        <%Imodec::Resource.send("#{pcat}_resources").each do |controller|%>
        <% unless @manager.super? %>
        <% if ['events', 'metas'].include?(controller.name)  %>
        <% next %>
        <% end %>
        <% end %>
        <li class="controller">
            <%if @manager.has_right_of(controller.name)%>
            <%=check_box_tag "#{controller.name}","",:checked%>
            <%else%>
            <%=check_box_tag "#{controller.name}"%>
            <%end%>
            <label for="<%=controller.name%>">
                <strong><%=controller.description%></strong>
            </label>


            <ul>
                <%controller.actions.each do |action|%>
                <li>
                    <%=f.check_box "#{controller.name}[#{action.name}]",:checked=>@manager.has_right_of(controller.name,action.name)%>
                    <label for='permission_<%="#{controller.name}[#{action.name}]"%>'>
                        <%=action.description%>
                    </label>

                </li>
                <%end%>
            </ul>
        </li>
        <%end%>
    </ul>
    <hr>
    <%end%>
    
</div>


<div class="form-actions">
    <%=f.submit "保存",:class=>"btn btn-primary"%>
    <%=link_to  "返回",admin_permissions_path,:class=>"btn"%>
</div>

<%end unless @manager.super?%>

app/views/admin/permissions/index.html.erb
<%=link_to "新建管理员",new_admin_permission_path%>
<% unless current_admin.super? %>
	<% @managers = @managers[1, @managers.length - 1] %>
	<% end %>
<table class="table table-bordered">
	<thead>
		<tr>
			<th>角色</th>
			<th>用户名</th>
			<th>超级管理员</th>
			<th>启用</th>
			<th>操作</th>
		</tr>
	</thead>
	<%@managers.each do |manager|%>	
	<tr>
		<td><%=manager.role_name%></td>
		<td><%=manager.account.login_name%></td>
		<td><%= (['0', '1'].include? manager.super) ? "是" : "否"%></td>
		<td><%=manager.status=="1" ? "是" : "否"%></td>
		<td>
		<% next if manager == current_admin.manager %>
		<span><%=link_to "权限管理",edit_admin_permission_path(manager) if ['0', '1'].include? current_admin.manager.super %></span>
		<span><%=link_to "角色管理",admin_permission_role_path(manager) if ['0', '1'].include? current_admin.manager.super %></span>
		<span><%=link_to "删除",admin_permission_path(manager), method: :delete if ['0', '1'].include? current_admin.manager.super %></span>
		</td>
	</tr>
	<%end%>
</table>

app/views/admin/permissions/new.html.erb
<h4>新建用户</h4>
<hr>
<%=render "form"%>

app/views/admin/permissions/role.html.erb
<%= form_for :manager,:url=>admin_user_path, :method=>:put, :html => {:class => "form-horizontal"} do |f| %>


<fieldset>
  <div class="control-group">
    <span>用户名</span>
    
      <span><%= @manager.account.login_name%></span>
    
  </div> 

  <div class="control-group">
  <%= f.label :super, "角色：", :class => "control-label" %>
    <div class="controls">
      <%=f.select(:super, [['超级管理员', '0'], ['审核员', '2'], ['文章发布员', '3']]) %>
    </div>
  </div>

  <div class="control-group">
    <div class="controls">
      <%= f.submit '确定', :class => "btn btn-primary" %>
      <%= link_to '返回', admin_tags_path,:class=>"btn" %>
    </div>
  </div>

</fieldset>
<% end %>





    

app/views/admin/permissions/update.html.erb
<h1>Admin::Permissions#update</h1>
<p>Find me in app/views/admin/permissions/update.html.erb</p>