config/routes.rb
require 'httpclient'
Modengke::Application.routes.draw do

 get 'articles/gyyx/gswh' => 'articles/gyyx#gswh'
 get 'articles/gyyx/gsgs' => 'articles/gyyx#gsgs'
 get 'articles/shzr/bzsy' => 'articles/shzr#bzsy'
 get 'articles/shzr/spaq' => 'articles/shzr#spaq'
 get 'articles/hzgy/hwys' => 'articles/hzgy#hwys'
 get 'articles/lxwm/zgzb' => 'articles/lxwm#zgzb'
 get 'articles/xwcx/xwdt' => 'articles/xwcx#xwdt'
 get 'articles/xwcx/xwdt/:id' => 'articles/xwcx#show'

 resources :contacts

 resources :cases

 resources :commissions do
  collection do
   get  'platform'
   get 'bank_info'
 end

 member do
  get 'paid'
end
end

mount WeixinRailsMiddleware::Engine, at: "/"

root :to=>"home#index",:constraints=>{ :subdomain=>/^(www)?$/ }
get 'blank'=>"home#blank"
get 'home'=>"home#index"

resources :pages, :only=>[:show]

namespace :auth do
  resources :accounts
  resources :weixin do
    get 'callback',:on=>:member
  end
  resources :weibo do
    get 'callback',:on=>:collection
  end
  resources :douban do
    get 'callback',:on=>:collection
  end
end

resources :sessions

get 'register'=>'users#new'
resources :users do
  get 'forgot_password', :on=>:collection
  post 'send_reset_password_instruction', :on=>:collection    
  get 'reset_password',:on=>:collection
  post 'search', :on=>:collection
  post 'change_password',:on=>:collection
  post 'update' ,:on=>:member
end

resources :vshop do
  collection do
    get 'login'
    get 'register'
    get 'article'
    get 'apply'
    post 'search'
    post 'change_password'
    get 'goods'
    get 'orders'
    get 'members'
    get 'weixin'
    post "destory"
  end
  member do
    get :user
    get :category
    get :commodity
    get :order
     get :payments
     get :native
     post :paynotifyurl
     get :paynotifyurl
     get :feedback
   end
 end

 get 'auto_login'=>"sessions#auto_login"
 get 'login'=>"sessions#login"
 get 'mlogin'=>"sessions#new_mobile"
 get 'mregister'=>"sessions#register_mobile"
 post 'login'=>"sessions#create"
 post 'mlogin'=>"sessions#create"
 get 'logout'=>"sessions#destroy"
 get 'topmenu'=>"home#topmenu"

 scope :module=> "events" do
  resources :user_survey, :controller=>"survey" do
    post "add_mobile", :on=>:collection
  end
end

namespace :events do
  resources :applicants
end

resources :events

scope :module => "blog" do
    root :to => "articles#index"
    resources :articles

  end

  scope :module => "magazine" do
    resources :topics do
      resources :pages
    end
    match '/more_topics' => 'topics#more'
    match '/list_topics' => 'topics#list'
    match '/flash' => 'flashes#index'
  end

  scope :module => "memberships" do
    match '/vip' => 'vip#index'
    resource  :card do
      collection do
        get 'search'

        get 'activation'
        post 'confirm_activation'
        post 'validate_activation'
        post 'activate'
        get 'complete_activation'
        post 'input_mobile'
        post 'select'
        put 'update_mobile'
        put 'modify_mobile'
        get 'cancel_mobile'

        get 'purchase'
        scope "purchase" do
          post 'confirm_buyer'
          post 'confirm_user'
          get 'user'
        end

        get 'send_sms_code'

      end
    end
    resources  :member_cards
  end

  get 'admin'=>'admin/sessions#new'

  namespace :admin do

    get 'logout'=>'sessions#destroy'
    resources :tracks do
      get :pages,:on=>:collection
    end

    resources :discount_codes

    resources :carts do

    end
    resources :wechat do
      get :menu,:on=>:collection
      get :menu_edit,:on=>:collection
      get :followers, :on=>:collection
      get :followers_import, :on=>:collection
      get :follower_renew,:on=> :collection
      get :groups, :on=>:collection
      get :batch_sending, :on=>:collection
      get :weixin,:on=>:collection
    end
    resources :resources
    resources :permissions do
    end
    get 'permissions/:id/role' => 'permissions#role', as: :permission_role

    resources :suppliers do
      get 'update_state',:on=>:collection
    end

    resources :sessions
    resources :coupons
    resources :goods_cats do
      get :create_top,:on=>:collection
      get :toggle_future,:on=>:member
      get :toggle_agent,:on=>:member
      get :toggle_sell,:on=>:member
      post :save_top,:on=>:collection
    end
    resources :goods_types do
      put :updateType,:on=>:member
    end
    resources :goods_labels do
      put :updateLabel,:on=>:member
      get :createLabel,:on=>:collection
    end

    resources :brand_adms do
      get :delete
      put :update_brand,:on=>:member
    end

    resources :goods do
      post "export", :on=>:collection
      post "import", :on=>:collection
      post "remove_spec_item",:on=>:member
      get "add_spec_item",:on=>:member
      get "spec",:on=>:member
      put "update_spec",:on=>:member
      get 'select_goods',:on=>:collection
      get 'collocation',:on=>:member
      get 'set_suits',:on=>:member
      get 'cancel_suits',:on=>:member
      post 'create_collocation',:on=>:collection
      get 'search', :on=>:collection
      get 'select_gifts',:on=>:collection
      put 'batch',:on=>:collection
      get 'select_all',:on=>:collection

      get :toggle_future,:on=>:member
      get :toggle_agent,:on=>:member
      get :toggle_sell,:on=>:member
    end
    resources :spec_items

    resources :images do
      post "mark", :on=>:collection
      post "rollback",:on=>:collection
      post "refresh",:on=>:collection
    end
    resources :articles do
      post 'set_position',:on=>:collection
    end
    resources :topics do
      post 'set_position',:on=>:collection
      post 'published_at',:on=>:member
    end
    resources :pages

    resources :members do
      post "export",:on=>:collection
      post "column_reload",:on=>:collection
      post "send_sms",:on=>:collection
      post "send_sms2",:on=>:collection
      get :info,:on=>:member
      put :updateInfo,:on=>:member
    end

    resources :cards do
      get 'buy',:on=>:member
      get 'use',:on=>:member
      get 'edit_user',:on=>:member
      get 'edit_pay',:on=>:member
      get 'logs', :on=>:member
      post 'import', :on=>:collection
      post "export",:on=>:collection
      get "tag",:on=>:collection
      put "untag",:on=>:member
      put "cancel_order",:on=>:member
    end

    resources :users do
      get 'search',:on=>:collection
      post 'newuser',:on=>:collection
      put 'send_sms_code',:on=>:member
      put 'buy_card',:on=>:member
      put 'use_card',:on=>:collection
      get 'select', :on=>:member
      put 'validate_mobile',:on=>:member
    end
    resources :member_cards

    resources :tag_exts

    resources :configs

    resources :labels

    resources :emails do
      get 'send_all',:on=>:collection
    end

    resources :categories

    resources :applicants

    resources :events do
      get 'applicants',:on=>:member
    end

    resources :homes

    resources :brand_pages do
      get 'toggle', :on=>:member
      put 'order', :on=>:member
      put 'reco', :on=>:member
    end

    resources :promotions

    resources :new_coupons do
      get 'download', :on=>:member
      get  'select_coupons', :on=>:collection
    end

    resources :user_coupons

    resources :orders do
      collection do
        get 'search'
        post :export
        put 'batch'
      end

      member do
        get 'detail'
        get 'pay'
        post 'dopay'
        get 'delivery'
        post 'dodelivery'
        get 'print_order'
        get 'print_preparer'
        get 'reship'
        post 'doreship'
        get 'refund'
        post 'dorefund'
        get :comment
        put :update_memo
      end
    end

    resources :static_pages
    resources :footers

    resources :metas

    resources :specifications

    resources :tags

    resources :offline_coupons do
      get 'downloads',:on=>:member
    end

    resources :virtual_goods do
      post 'import', :on=>:collection
    end

    resources :payment_logs

  end
  get 'm' =>"mobile#show", :as=>"mobile" ,:controller=>"mobile"

  scope :module => "store" do

    get 'search' => "search#index", :as=> :search
    get 'mproducts' =>"goods#mproduct", :as=>"goods" ,:controller=>"goods"

    resources :products, :as=>"goods", :controller=>"goods" do
      get 'newest',:on=>:collection
      put 'fav',:on=>:member
      put 'unfav',:on=>:member
      get 'price',:on=>:member
      get 'more',:on=>:collection
      get 'suits', :on=>:collection
      get 'more_suits', :on=>:collection

    end

    resources :suppliers

    resources :coupons, :controller=>"offline_coupons" do
      post 'download',:on=>:member
    end

    resources :vgoods, :controller=>"virtual_goods",:only=>[:index,:show]
    post 'cart/add'=>"cart#add",:as=>:add_to_cart

    resources :cart do
      get 'manco_express'  ,:on=>:collection
      get 'distribution_manco',:on=>:collection
      post 'add',:on=>:collection
      get 'mobile', :on=>:collection
    end
    resources :brands,:only=>[:index,:show]
    resources :users
    resources :vshop
    resources :country, :as=>"countries", :controller=>"countries"
    resources :gallery, :as=>"cats", :controller=>"cats"

    get 'mgallery' =>"cats#show_mobile", :as=>"cats",:controller=>"cats"
    get 'mgoods_list'=>"cats#goods_list" ,:as=>"cats", :controller=>"cats"
    resources :goods,  :as=>"orders", :controller=>"orders" do
      member do
        get :goods
      end
    end

    get 'share' =>"orders#share"

    resources :orders, :except=>[:index] do
      member do
        get 'to_inventory'
        get 'out_inventory'
        post :pay
        get :detail
        get :goods

      end

      collection do
        post 'destroyaddr'
        get 'check_coupon'
        get  'new_mobile'
        get  'new_tairyo'

        post 'new_manco'
        get 'new_mobile_addr'
        get 'new_manco_addr'
        get 'departure'
        post 'arrival'
        get 'arrival'

app/helpers/admin/orders_helper.rb
#encoding:utf-8
module Admin::OrdersHelper
	def payment_options
		{"bcom"=>"交通银行在线支付",
		"icbc"=>"工商银行在线支付",
		"deposit"=>"预存款支付",
		"offline"=>"货到付款",
		"99bill"=>"快钱网上支付",
		"alipay"=>"支付宝支付",
    "ips"=>"环迅人民币支付"}
	end
end

app/helpers/store/orders_helper.rb
#encoding:utf-8
module Store::OrdersHelper

	def ship_day_options
		{      "任意日期"=>"任意日期",
			"仅工作日"=>"仅工作日",
			"仅休息日"=>"仅休息日",
			"指定日期"=>"special"  }
	end

	def ship_time_options
		{     "任意时间段"=>"任意时间段",
			"上午"=>"上午",
			"下午"=>"下午",
			"晚上"=>"晚上"  }
	end


	def payments
		{
      "term"=>{ :name=>"账期支付",:extra=>"与供应商协商"},
      "ips"=>{ :name=>"环迅人民币支付",:extra=>""},
			"bcom"=>{ :name=>"交通银行网上支付", :extra=>"持交通银行卡在线支付可享受订单金额95折优惠" },
			"icbc"=>{ :name=>"工商银行网上支付", :extra=>'申请分期付款 (<span class="highlight">申请信用卡分期付款，超低手续费，月还款无压力！</span>)' },
			"deposit"=>{ :name=>"预存款", :extra=>"" },
			"offline"=>{ :name=>"货到付款", :extra=>link_to("点击查询货到付款配送区域","http://www.zjs.com.cn/WS_Business/WS_Bussiness_CityArea.aspx?id=6",:target=>"_blank").html_safe }, 
			"99bill"=>{ :name=>"其他银行网上支付",:extra=>"" },
			"alipay"=>{ :name=>"支付宝",:extra=>"" },
      "alipaywap"=>{ :name=>"支付宝手机版",:extra=>"" },
      "wxpay"=>{:name=>"微信支付",:extra=>""}
		}
	end
end

app/views/admin/orders/_filter.html.erb
<%=form_for :s,:url=>search_admin_orders_path,:method=>:get,:html=>{:class=>"form-search"} do |f|%>
<%=f.text_field :q, :value=>params[:s]&&params[:s][:q],:placeholder=>"订单号/收货人"%>
<input type="submit" value="搜索" class="btn btn-success">
<%=link_to "清除",admin_orders_path,:class=>"btn"%>
<%end%>

app/views/admin/orders/_order_tr.html.erb
<tr class="<%=order.status%>" id="order_<%=order.order_id%>">
	<td>
		<%= check_box_tag nil, order.order_id, false,:id=>"check_#{order.order_id}",:class=>"order"%>
	</td>
	<td><%=order.order_id%></td>
	
	<td><%=link_to "详细",detail_admin_order_path(order),:target=>"_blank"%></td>
  <%if current_admin.has_right_of("orders","delivery")%>
	<td class="dropdown">
		<%if order.status == "active"%>
			<%=link_to "#",:class=>"dropdown-toggle",:data=>{:toggle=>"dropdown"} do%>
				订单操作 <b class="caret"></b>
			<%end%>
			<ul class="dropdown-menu">
				<!-- <li><%=link_to "编辑",edit_admin_order_path(order),:target=>"_blank" if order.status == 'active'%></li> -->
				
				<li>
					<%=link_to "支付",pay_admin_order_path(order,:page=>params[:page]) if order.pay_status == '0'%>

					<%link_to "支付",pay_admin_order_path(order,:page=>params[:page]),:data=>{:target=>"#ajax_modal",:remote=>pay_admin_order_path(order) },:class=>"remote-modal" if order.pay_status == '0'%>
				</li>

				<li><%=link_to "退款", refund_admin_order_path(order,:page=>params[:page]) unless %w(0 5).include?(order.pay_status)%></li>

				<li><%=link_to "发货",delivery_admin_order_path(order,:page=>params[:page]) if ['0','2'].include?(order.ship_status)%></li>

				<li>
					<%=link_to "退货",reship_admin_order_path(order,:page=>params[:page]) if !['0','4'].include?(order.ship_status)%>
				</li>

				<li><%=link_to "完成",admin_order_path(order,:order=>{:status=>'finish'}),:method=>:put,:remote=>true,:confirm=>"完成操作会将该订单归档并且不允许再做任何操作，确认要执行吗?" if order.status == 'active'%></li>
				<li><%=link_to "作废",admin_order_path(order,:order=>{:status=>'dead'}),:method=>:put,:remote=>true,:confirm=>"作废后该订单将不能做任何操作，确认要执行吗?" if order.status == 'active'%></li>
				<li>
					<%=link_to "订单备注",comment_admin_order_path(order,:page=>params[:page])%>
				</li>
                <li>
                  <%= link_to '删除', admin_order_path(order), method: :delete, data: { confirm: 'Are you sure?' } %>
                </li>
				</ul>
			<%end%>
	</td>
	<td>
		<%=link_to "购", print_order_admin_order_path(order),:target=>"_blank"%>
		<%=link_to "配", print_preparer_admin_order_path(order),:target=>"_blank"%>
	</td>
      <%end%>
	<td>
		<%order.tegs.each do |teg|%>
			<span class="teg" style="background-color:<%=teg.tag_bgcolor%>;color:<%=teg.tag_fgcolor%>">
				<%=teg.tag_name%>
			</span>
		<%end%>
	</td>
	<td><%=order.user.login_name if order.user%></td>
	<td><%=order.created_at%></td>
	<td><%=order.payment_name%></td>
	<td><%=order.status_text%></td>
	<td><%=order.pay_status_text%></td>
	<td><%=order.ship_status_text%></td>
	<td><%=number_to_currency order.final_amount,:unit=>"&yen;",:precision=>2%></td>
    <td><%#=number_to_currency order.commission,:unit=>"&yen;",:precision=>2 if order.desktop_user_id || order.recommend_user%></td>
    <td><%=number_to_currency order.cost_freight,:unit=>"&yen;",:precision=>2%></td>
	<td><%=order.ship_name%></td>
	<td><%=order.ship_addr%></td>
	<td><%=order.ship_mobile%></td>
</tr>
<%#@total_commission +=order.commission%>
<%@total +=order.final_amount%>

app/views/admin/orders/_pay_form.html.erb
<%=form_for :payment, :url=>dopay_admin_order_path(@order,:return_url=>@return_url), :html=>{ :class=>"form-horizontal" } do |f|%>

  <div class="control-group">
    <label class="control-label">订单号:</label>
    <div class="controls">
     	<span class="readonly-field"><%=@order.order_id%> (<%=@order.pay_status_text%>)</span>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">会员:</label>
    <div class="controls">
     	<span class="readonly-field"><%=@order.user.login_name if @order.user%></span>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">订单金额:</label>
    <div class="controls">
     	<span class="readonly-field">&yen;<%=@order.final_amount.to_i%></span>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">已收金额:</label>
    <div class="controls">
     	<span class="readonly-field">&yen;<%=@order.part_pay.to_i%></span>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">收款金额:</label>
    <div class="controls">
     	<%=f.number_field :money,:value=>@order.final_amount,:class=>"input-small"%>
    </div>
  </div>

   <div class="control-group">
    <label class="control-label">支付方式:</label>
    <div class="controls">
     	<select class="span2" id="payment_pay_app_id" name="payment[pay_app_id]">
     		<option value="">请选择</option>
     		<%payment_options.each do |value,text|%>
		<option value="<%=value%>" <%='selected' if value == @order.payment%> ><%=text%></option>
		<%end%>
	</select>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">交易号:</label>
    <div class="controls">
     	<%=f.text_field :trade_no%>
    </div>
  </div>

   <div class="control-group">
    <label class="control-label">付款人:</label>
    <div class="controls">
     	<%=f.text_field :pay_account%>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label">备注:</label>
    <div class="controls">
     	<%=f.text_field :memo,:class=>"span4"%>
    </div>
  </div>

   <div class="control-group">
    <label class="control-label"></label>
    <div class="controls">
     	<%=f.submit "提交",:class=>"btn btn-primary" if @order.pay_status == '0'%>
     	<a href="<%=@return_url%>" class="btn" data-dismiss="modal">取消</a>
    </div>
  </div>
  

<%end%>

app/views/admin/orders/comment.html.erb
<%= form_for @order,:url => update_memo_admin_order_path, :html => {:class => "form-horizontal"} do |f| %>
  
  <fieldset>
    <div class="control-group">
      <%= f.label :order_id, "订单号", :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :order_id,:readonly=>true%>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :memo, "订单备注", :class => "control-label" %>
      <div class="controls">
        <%= f.text_area :memo%>
      </div>
    </div>
    
    <div class="control-group">
      <div class="controls">
        <%= f.submit '确定', :class => "btn btn-primary" %>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to '返回', admin_orders_path %>
      </div>
    </div>

  </fieldset>
<% end %>

app/views/admin/orders/delivery.html.erb
<div id="delivery">
   <h4>发货 : <%=@order.order_id%></h4>
   <hr>

    <%=form_for :delivery, :url=>dodelivery_admin_order_path(@order,:return_url=>@return_url), :html=>{ :class=>"form-horizontal" } do |f|%>
      <%=f.hidden_field :order_id,:value=>@order.order_id%>
      <%=f.hidden_field :member_id,:value=>@order.member_id%>
      <%=f.hidden_field :op_name,:value=>current_admin.login_name if current_admin%>
      <%=f.hidden_field :delivery,:value=>1%>

      <div class="control-group">
        <label class="control-label">订单号:</label>
        <div class="controls">
         	<span class="readonly-field"><%=@order.order_id%> (<%=@order.ship_status_text%>)</span>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label">会员:</label>
        <div class="controls">
         	<span class="readonly-field"><%=@order.user.login_name if @order.user%></span>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label">下单时间:</label>
        <div class="controls">
          <span class="readonly-field"><%=@order.created_at%></span>
        </div>
      </div>
     <% unless @order.supplier_id==(Ecstore::Supplier.find_by_name("万家物流").id)%>
      <div class="control-group">
        <label class="control-label">物流公司:</label>
        <div class="controls">
         	<%=f.select :logi_id,Ecstore::Dlycorp.order("ordernum asc").all.collect{|c| [c.name,c.corp_id]},{:include_blank=>"请选择"},{:class=>"span2"}%>
            <%=f.hidden_field :logi_name%>
            <span class="help-inline error"><%=@delivery.errors[:logi_id].join(",")%></span>
        </div>
      </div>

       <div class="control-group">
        <label class="control-label">物流单号:</label>
        <div class="controls">
          <%=f.text_field :logi_no%>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label">物流费用:</label>
        <div class="controls">
         	<%=f.number_field :money,:value=>0,:class=>"input-small"%>
        </div>
      </div>

       <div class="control-group">
        <label class="control-label">物流保价:</label>
        <div class="controls">
          <label class="radio inline"><%=f.radio_button :is_protect,'true',:checked=>true%>是</label>
          <label class="radio inline"><%=f.radio_button :is_protect,'false'%>否</label>
          
        </div>
      </div>
        <%end%>
      <div class="control-group">
          <%=f.label :ship_area, "收货地区:".html_safe,:class=>"control-label"%>
          <div class="controls area">

            <%=f.select :province,options_from_collection_for_select(Ecstore::Region.provinces,:region_id,:local_name,@order.province),{:include_blank=>"请选择省" },{ :onchange=>"selectProvince(this,'#city','#district');",:id=>"province",:class=>"span2" }%>
            
            <%if @order&&@order.city%>
                <%=f.select :city,options_from_collection_for_select(Ecstore::Region.cities_of(@order.province),:region_id,:local_name,@order.city),{:include_blank=>"请选择市"},{ :onchange=>"selectCity(this,'#district');",:id=>"city",:class=>"span2" }%>
            <%else%>
                    <%=f.select :city, {}, { :include_blank=>"请选择市" }, { :onchange=>"selectCity(this,'#district');",:id=>"city",:class=>"span2" }%>
            <%end%>

            <%if @order&&@order.district%>
              <%=f.select :district,options_from_collection_for_select(Ecstore::Region.districts_of(@order.city),:region_id,:local_name,@order.district),{:include_blank=>"请选择区/县"},{ :onchange=>"selectDistrict(this);",:id=>"district" }%>
            <%else%>
              <%=f.select :district, {}, { :include_blank=>"请选择区/县" }, { :onchange=>"selectDistrict(this);",:id=>"district" }%>
            <%end%>

             <span class="help-inline error"><%=@delivery.errors[:ship_area].join(",")%></span>
          </div>
      </div>


      <% if @order.supplier_id==(Ecstore::Supplier.find_by_name("万家物流").id)%>
        <div style="border: 1px solid#0000ee">
          <div class="control-group">
            <label class="control-label">寄货人:</label>
            <div class="controls">
              <span class="readonly-field"><%=@order.from_addr.split(",")[0]%> </span>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label">手机号码:</label>
            <div class="controls">
              <span class="readonly-field"><%=@order.from_addr.split(",")[1]%> </span>
            </div>
          </div>
        <div class="control-group">
          <label class="control-label">寄货人地址:</label>
          <div class="controls">
            <span class="readonly-field"><%=@order.from_addr.split(",")[2]%> </span>
          </div>
        </div>
        </div>
            <%end%>
      <div class="control-group ">
          <%=f.label :ship_zip, "邮编:",:class=>"control-label"%>
          <div class="controls zip">
            <%=f.text_field :ship_zip,:class=>"input-small"%>
          </div>
      </div>

      <div class="control-group ">
          <%=f.label :ship_name, "收货人:".html_safe,:class=>"control-label"%>
          <div class="controls name">
            <%=f.text_field :ship_name,:class=>"input-small"%>
            <span class="help-inline error"><%=@delivery.errors[:ship_name].join(",")%></span>
          </div>

      </div>

      <div class="control-group ">
          <%=f.label :ship_mobile, "手机:".html_safe,:class=>"control-label"%>
          <div class="controls mobile">
            <%=f.text_field :ship_mobile,:class=>"span2",:maxlength=>11%>
            <span class="help-inline error"><%=@delivery.errors[:ship_mobile].join(",")%></span>
          </div>
      </div>
    <div class="control-group ">
      <%=f.label :ship_addr, "收货地址:".html_safe,:class=>"control-label"%>
      <div class="controls addr">
        <%=f.text_field :ship_addr,:class=>"span5"%>
        <span class="help-inline error"><%=@delivery.errors[:ship_addr].join(",")%></span>
      </div>
    </div>
      <div class="control-group ">
          <%=f.label :ship_tel, "固定电话:",:class=>"control-label"%>
          <div class="controls tel">
            <%=f.text_field :ship_tel,:class=>"span2"%>
          </div>
      </div>


      <div class="control-group">
        <label class="control-label">发货备注:</label>
        <div class="controls">
          <%=f.text_area :memo,:class=>"span4",:rows=>2%>
        </div>
      </div>  
      

      <div class="delivery-items">
            <table class="table table-bordered">
              <tr>
                <th>货号</th>
                <th>商品名称</th>
                <th>当前库存</th>
                <th>购买数量</th>
                <th>已发货</th>
                <th>此单发货</th>
              </tr>
            
            <%@order.order_items.each do |order_item|%>

                <tr>
                    <td><%=order_item.bn%></td>
                    <td><%=order_item.name%></td>
                    <td><%=order_item.product.store%></td>
                    <td><%=order_item.nums%></td>
                    <td><%=order_item.sendnum%></td>
                    <td>
                        <%if order_item.sendnum < order_item.nums%>

                            <%=f.fields_for "delivery_items[]", @delivery.delivery_items do |items|%>
                              <%=items.hidden_field "order_item_id",:value=>order_item.item_id%>
                              <%=items.hidden_field :item_type,:value=>order_item.item_type == "product" ? "goods" : order_item.item_type%>
                              <%=items.hidden_field :product_id,:value=>order_item.product_id%>
                              <%=items.hidden_field :product_bn,:value=>order_item.bn%>
                              <%=items.hidden_field :product_name,:value=>order_item.name%>
                              <%=items.text_field :number,:value=>order_item.nums - order_item.sendnum,:class=>"input-mini"%>
                            <%end%>
                            
                         <%else%>
                            已经发货
                         <%end%>
                    </td>
                </tr>
            <%end%>
            
            </table>
      </div>



       <div class="control-group">
        <label class="control-label"></label>
        <div class="controls">
         	<%=f.submit "提交",:class=>"btn btn-primary" if ['0','2'].include?(@order.ship_status) %>
            <%=link_to "取消","#{@return_url}",:class=>"btn"%>
        </div>
      </div>
    <%end%>
</div>

app/views/admin/orders/dopay.js.erb
alert('付款成功');
$('#ajax_modal').modal('hide');
$("#order_<%=@order.order_id%>").replaceWith('<%=j render :partial=>"order_tr",:locals=>{ :order=>@order }%>');

app/views/admin/orders/index.js.erb
$("#orders tbody").html('<%= j render(:partial=>"order_tr",:collection=>@orders,:as=>:order)%>');
$(".pagination").html('<%= j will_paginate(@orders,:container=>false)%>');
$("#orders").attr("data-url","<%=request.fullpath%>");
window.location.hash = "#page=<%=params[:page] || 1%>";

app/views/admin/orders/pay.html.erb
<div id="pay">
	<h4>支付 : <%=@order.order_id%></h4>
   	<hr>
	<%=render "pay_form"%>
</div>