config/routes.rb
require 'httpclient'
Modengke::Application.routes.draw do

 get 'articles/gyyx/gswh' => 'articles/gyyx#gswh'
 get 'articles/gyyx/gsgs' => 'articles/gyyx#gsgs'
 get 'articles/shzr/bzsy' => 'articles/shzr#bzsy'
 get 'articles/shzr/spaq' => 'articles/shzr#spaq'
 get 'articles/hzgy/hwys' => 'articles/hzgy#hwys'
 get 'articles/lxwm/zgzb' => 'articles/lxwm#zgzb'
 get 'articles/xwcx/xwdt' => 'articles/xwcx#xwdt'
 get 'articles/xwcx/xwdt/:id' => 'articles/xwcx#show'

 resources :contacts

 resources :cases

 resources :commissions do
  collection do
   get  'platform'
   get 'bank_info'
 end

 member do
  get 'paid'
end
end

mount WeixinRailsMiddleware::Engine, at: "/"

root :to=>"home#index",:constraints=>{ :subdomain=>/^(www)?$/ }
get 'blank'=>"home#blank"
get 'home'=>"home#index"

resources :pages, :only=>[:show]

namespace :auth do
  resources :accounts
  resources :weixin do
    get 'callback',:on=>:member
  end
  resources :weibo do
    get 'callback',:on=>:collection
  end
  resources :douban do
    get 'callback',:on=>:collection
  end
end

resources :sessions

get 'register'=>'users#new'
resources :users do
  get 'forgot_password', :on=>:collection
  post 'send_reset_password_instruction', :on=>:collection    
  get 'reset_password',:on=>:collection
  post 'search', :on=>:collection
  post 'change_password',:on=>:collection
  post 'update' ,:on=>:member
end

resources :vshop do
  collection do
    get 'login'
    get 'register'
    get 'article'
    get 'apply'
    post 'search'
    post 'change_password'
    get 'goods'
    get 'orders'
    get 'members'
    get 'weixin'
    post "destory"
  end
  member do
    get :user
    get :category
    get :commodity
    get :order
     get :payments
     get :native
     post :paynotifyurl
     get :paynotifyurl
     get :feedback
   end
 end

 get 'auto_login'=>"sessions#auto_login"
 get 'login'=>"sessions#login"
 get 'mlogin'=>"sessions#new_mobile"
 get 'mregister'=>"sessions#register_mobile"
 post 'login'=>"sessions#create"
 post 'mlogin'=>"sessions#create"
 get 'logout'=>"sessions#destroy"
 get 'topmenu'=>"home#topmenu"

 scope :module=> "events" do
  resources :user_survey, :controller=>"survey" do
    post "add_mobile", :on=>:collection
  end
end

namespace :events do
  resources :applicants
end

resources :events

scope :module => "blog" do
    root :to => "articles#index"
    resources :articles

  end

  scope :module => "magazine" do
    resources :topics do
      resources :pages
    end
    match '/more_topics' => 'topics#more'
    match '/list_topics' => 'topics#list'
    match '/flash' => 'flashes#index'
  end

  scope :module => "memberships" do
    match '/vip' => 'vip#index'
    resource  :card do
      collection do
        get 'search'

        get 'activation'
        post 'confirm_activation'
        post 'validate_activation'
        post 'activate'
        get 'complete_activation'
        post 'input_mobile'
        post 'select'
        put 'update_mobile'
        put 'modify_mobile'
        get 'cancel_mobile'

        get 'purchase'
        scope "purchase" do
          post 'confirm_buyer'
          post 'confirm_user'
          get 'user'
        end

        get 'send_sms_code'

      end
    end
    resources  :member_cards
  end

  get 'admin'=>'admin/sessions#new'

  namespace :admin do

    get 'logout'=>'sessions#destroy'
    resources :tracks do
      get :pages,:on=>:collection
    end

    resources :discount_codes

    resources :carts do

    end
    resources :wechat do
      get :menu,:on=>:collection
      get :menu_edit,:on=>:collection
      get :followers, :on=>:collection
      get :followers_import, :on=>:collection
      get :follower_renew,:on=> :collection
      get :groups, :on=>:collection
      get :batch_sending, :on=>:collection
      get :weixin,:on=>:collection
    end
    resources :resources
    resources :permissions do
    end
    get 'permissions/:id/role' => 'permissions#role', as: :permission_role

    resources :suppliers do
      get 'update_state',:on=>:collection
    end

    resources :sessions
    resources :coupons
    resources :goods_cats do
      get :create_top,:on=>:collection
      get :toggle_future,:on=>:member
      get :toggle_agent,:on=>:member
      get :toggle_sell,:on=>:member
      post :save_top,:on=>:collection
    end
    resources :goods_types do
      put :updateType,:on=>:member
    end
    resources :goods_labels do
      put :updateLabel,:on=>:member
      get :createLabel,:on=>:collection
    end

    resources :brand_adms do
      get :delete
      put :update_brand,:on=>:member
    end

    resources :goods do
      post "export", :on=>:collection
      post "import", :on=>:collection
      post "remove_spec_item",:on=>:member
      get "add_spec_item",:on=>:member
      get "spec",:on=>:member
      put "update_spec",:on=>:member
      get 'select_goods',:on=>:collection
      get 'collocation',:on=>:member
      get 'set_suits',:on=>:member
      get 'cancel_suits',:on=>:member
      post 'create_collocation',:on=>:collection
      get 'search', :on=>:collection
      get 'select_gifts',:on=>:collection
      put 'batch',:on=>:collection
      get 'select_all',:on=>:collection

      get :toggle_future,:on=>:member
      get :toggle_agent,:on=>:member
      get :toggle_sell,:on=>:member
    end
    resources :spec_items

    resources :images do
      post "mark", :on=>:collection
      post "rollback",:on=>:collection
      post "refresh",:on=>:collection
    end
    resources :articles do
      post 'set_position',:on=>:collection
    end
    resources :topics do
      post 'set_position',:on=>:collection
      post 'published_at',:on=>:member
    end
    resources :pages

    resources :members do
      post "export",:on=>:collection
      post "column_reload",:on=>:collection
      post "send_sms",:on=>:collection
      post "send_sms2",:on=>:collection
      get :info,:on=>:member
      put :updateInfo,:on=>:member
    end

    resources :cards do
      get 'buy',:on=>:member
      get 'use',:on=>:member
      get 'edit_user',:on=>:member
      get 'edit_pay',:on=>:member
      get 'logs', :on=>:member
      post 'import', :on=>:collection
      post "export",:on=>:collection
      get "tag",:on=>:collection
      put "untag",:on=>:member
      put "cancel_order",:on=>:member
    end

    resources :users do
      get 'search',:on=>:collection
      post 'newuser',:on=>:collection
      put 'send_sms_code',:on=>:member
      put 'buy_card',:on=>:member
      put 'use_card',:on=>:collection
      get 'select', :on=>:member
      put 'validate_mobile',:on=>:member
    end
    resources :member_cards

    resources :tag_exts

    resources :configs

    resources :labels

    resources :emails do
      get 'send_all',:on=>:collection
    end

    resources :categories

    resources :applicants

    resources :events do
      get 'applicants',:on=>:member
    end

    resources :homes

    resources :brand_pages do
      get 'toggle', :on=>:member
      put 'order', :on=>:member
      put 'reco', :on=>:member
    end

    resources :promotions

    resources :new_coupons do
      get 'download', :on=>:member
      get  'select_coupons', :on=>:collection
    end

    resources :user_coupons

    resources :orders do
      collection do
        get 'search'
        post :export
        put 'batch'
      end

      member do
        get 'detail'
        get 'pay'
        post 'dopay'
        get 'delivery'
        post 'dodelivery'
        get 'print_order'
        get 'print_preparer'
        get 'reship'
        post 'doreship'
        get 'refund'
        post 'dorefund'
        get :comment
        put :update_memo
      end
    end

    resources :static_pages
    resources :footers

    resources :metas

    resources :specifications

    resources :tags

    resources :offline_coupons do
      get 'downloads',:on=>:member
    end

    resources :virtual_goods do
      post 'import', :on=>:collection
    end

    resources :payment_logs

  end
  get 'm' =>"mobile#show", :as=>"mobile" ,:controller=>"mobile"

  scope :module => "store" do

    get 'search' => "search#index", :as=> :search
    get 'mproducts' =>"goods#mproduct", :as=>"goods" ,:controller=>"goods"

    resources :products, :as=>"goods", :controller=>"goods" do
      get 'newest',:on=>:collection
      put 'fav',:on=>:member
      put 'unfav',:on=>:member
      get 'price',:on=>:member
      get 'more',:on=>:collection
      get 'suits', :on=>:collection
      get 'more_suits', :on=>:collection

    end

    resources :suppliers

    resources :coupons, :controller=>"offline_coupons" do
      post 'download',:on=>:member
    end

    resources :vgoods, :controller=>"virtual_goods",:only=>[:index,:show]
    post 'cart/add'=>"cart#add",:as=>:add_to_cart

    resources :cart do
      get 'manco_express'  ,:on=>:collection
      get 'distribution_manco',:on=>:collection
      post 'add',:on=>:collection
      get 'mobile', :on=>:collection
    end
    resources :brands,:only=>[:index,:show]
    resources :users
    resources :vshop
    resources :country, :as=>"countries", :controller=>"countries"
    resources :gallery, :as=>"cats", :controller=>"cats"

    get 'mgallery' =>"cats#show_mobile", :as=>"cats",:controller=>"cats"
    get 'mgoods_list'=>"cats#goods_list" ,:as=>"cats", :controller=>"cats"
    resources :goods,  :as=>"orders", :controller=>"orders" do
      member do
        get :goods
      end
    end

    get 'share' =>"orders#share"

    resources :orders, :except=>[:index] do
      member do
        get 'to_inventory'
        get 'out_inventory'
        post :pay
        get :detail
        get :goods

      end

      collection do
        post 'destroyaddr'
        get 'check_coupon'
        get  'new_mobile'
        get  'new_tairyo'

        post 'new_manco'
        get 'new_mobile_addr'
        get 'new_manco_addr'
        get 'departure'
        post 'arrival'
        get 'arrival'

app/models/imodec/topic.rb
#encoding : utf-8
class Imodec::Topic < ActiveRecord::Base
  COVER_SIZES = ['big', 'normal', 'small']

  has_many :pages
  has_many :comments, :foreign_key=>"commentable_id",:class_name=>"Ecstore::Comment"

  belongs_to :category

 

  extend FriendlyId
  friendly_id :slug
  # require "babosa"

  # validates_presence_of :title, :slug, :body
  attr_accessor :remove_cover
  attr_accessible :body, :published, :title, :summary, :cover, :remove_cover, :cover_size,:require_login,:pages,:category_id,:slug,:page_keywords,:page_description,:commentable
  has_attached_file :cover,
        :styles => { :small => "230x112#", :normal => "230x230#", :big => "465x230#" },
        :default_url => "/assets/blog/default_cover1.gif"

  before_save :perform_cover_removal

  def normalize_friendly_id(input)
    input.to_s.to_slug.normalize().to_s
  end

  def perform_cover_removal
    self.cover = nil if self.remove_cover=="1"
    true
  end

  def self.published
    self.where(:published=>true).where("published_at <= :now", {:now=>Time.now} )
  end

  def pages=(inner_pages)
      inner_pages.each do |page|
          if page.is_a?(Hash)
             epage =  Imodec::Page.find(page[:id])
            
             self.pages.delete_if { |p| p.id == epage.id }
             epage.body = page[:body]
             self.pages << epage
          else
             self.pages  << Imodec::Page.new(:body=>page) if page.strip.size > 0
          end
          
      end
  end

end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < Admin::BaseController
  before_filter :require_permission!
  def index
    @topics = Imodec::Topic.paginate(:page => params[:page], :per_page => 20).order("created_at DESC")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  def new
    @topic = Imodec::Topic.new
    @create_or_update_path = admin_topics_path

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  def edit

    @topic = Imodec::Topic.find(params[:id])
    @create_or_update_path = admin_topic_path(@topic)
  end

  def create
    @topic = Imodec::Topic.new(params[:imodec_topic])

    if @topic.published
      @topic.published_at = Time.now
    end

    respond_to do |format|
      if @topic.save
        format.html { redirect_to edit_admin_topic_url(@topic), notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @topic = Imodec::Topic.find(params[:id])
    if params[:imodec_topic] && params[:imodec_topic][:published] && @topic.published_at == nil
      @topic.published_at = Time.now
    end

    respond_to do |format|
      if @topic.update_attributes(params[:imodec_topic])
        format.html { redirect_to edit_admin_topic_url(@topic), notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @topic = Imodec::Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to admin_topics_url }
      format.json { head :no_content }
    end
  end

  def set_position
    @topic = ::Imodec::Topic.find(params[:id])
    @topic_prev = ::Imodec::Topic.find_by_position_id(params[:position_id])
    if @topic_prev
      @topic_prev.position_id = nil
    end
    
    respond_to do |format|
      if @topic.update_attribute("position_id", params[:position_id].to_i)
        if @topic_prev
          @topic_prev.save!
          format.json { render json: {topic_prev_id: @topic_prev.id} }
        else
          format.json { render json: {topic_prev_id: 0} }
        end
      else
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  def published_at
      @topic = ::Imodec::Topic.find(params[:id])
      @topic.update_attribute :published_at,params[:published_at]
      render :nothing=>true
  end

end

app/controllers/magazine/topics_controller.rb
#encoding:utf-8
require 'pp'
class Magazine::TopicsController < Magazine::BaseController
  # layout nil, :only => [:more]

  # skip_before_filter :authorize_user!, :only=>[:show, :list]

  # before_filter :authorize_topic,:only=>[:show]

  def index
    if params[:category_id].present?
        @cat = Imodec::Category.find_by_id(params[:category_id])
        @topics = Imodec::Topic.where(:category_id=>params[:category_id])
    else
        @topics = Imodec::Topic.joins(:category).where("categories.name <> ?", "摩登报道")
    end

    @topics = @topics.published.paginate(:page => params[:page], :per_page => 20).order("created_at DESC") 
    
  end

  def show
    @topic = Imodec::Topic.find(params[:id])
    @comments = @topic.comments.paginate(:page => params[:page], :per_page => 3,:order=>"created_at desc")
    # render :layout=>"new_magazine" if @topic.body.blank?
  end

  def more
    # layout nil
    if params[:category_id].present?
        @topics = Imodec::Topic.where(:category_id=>params[:category_id])
    else
        @topics = Imodec::Topic.joins(:category).where("categories.name <> ?","摩登报道")
    end
    
    @topics = @topics.published.paginate(:page => params[:page], :per_page => 20).order("created_at DESC")
    render :layout=>nil
  end

  def list
  	@topics = Imodec::Topic.where(:cover_size=>"big", :published => true).paginate(:page => params[:page], :per_page => 9).order("created_at DESC")
  	@topics.each do |topic|
      topic.body = topic.cover.url(topic.cover_size)
      format="%Y-%m-%d"
      topic.title = topic.created_at.strftime(format)
      topic.summary = @topics.total_pages
    end
	  respond_to do |format|
        format.xml { render xml: @topics, :status => :ok}
    end
  end

  private 
  def authorize_topic
     topic = Imodec::Topic.find(params[:id])
     return authorize_user! if topic.require_login
  end

end

app/views/admin/topics/_form.html.erb
<%= form_for @topic,:url => @create_or_update_path, :html => {:class => "form-horizontal"} do |f| %>
  <fieldset>
    <% if @topic.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

        <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="control-group">
      <%= f.label :title, "标题", :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :title, :placeholder => "标题" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :slug, "链接名称", :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :slug, :placeholder => "链接名称" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :title, "分类", :class => "control-label" %>
      <div class="controls">
        <%= f.select :category_id,Imodec::Category.all.collect{|c| [c.name,c.id]},{:include_blank=>"请选择"}%>
        <%=link_to "添加分类","javascript:void(0);",:"data-url"=>admin_categories_path,:class=>"dialog"%>
      </div>
    </div>

  <%if @topic.new_record?%>
  <div class="control-group">
      <%= f.label :type, "形式", :class => "control-label" %>
      <div class="controls">
        <%= select_tag :type,"<option value='origin'>原始</option><option value='page'>内页</option>".html_safe,:class=>"topic-kind" %>
      </div>
    </div>
    <%end%>


    <div class="control-group">
      <%= f.label :body, "内容", :class => "control-label" %>
      <div class="controls">
        <%unless @topic.new_record?%>
             <%if @topic.body.present?%>
                  <%= f.cktext_area :body, :toolbar => 'Easy',:language=>'zh-cn',:height => 300 %>
             <%else%>
                  <%@topic.pages.each do |page|%>
                    <span id="page_<%=page.id%>">
                        <%=hidden_field_tag "imodec_topic[pages][][id]",page.id%>
                        <%=text_area_tag "imodec_topic[pages][][body]",page.body,:class=>"span6 page-area",:rows => "5"%>
                        <%=link_to "X",admin_page_path(page),:remote=>true,:method=>:delete,:class=>"remote-delete"%>
                    </span>
                  <%end%>
                  <div>
                  <%=link_to "+添加内页","#",:id=>"add_page"%>
                  </div>
              <%end%>
        <%else%>
            <%= f.cktext_area :body, :toolbar => 'Easy',:language=>'zh-cn',:height => 300 %>

            <div id="page-bodies" class="hide">
                 <span>
                        <%=text_area_tag "imodec_topic[pages][]","",:class=>"span6 page-area",:rows => "5"%>
                        <%=link_to "X","#",:class=>"delete-page"%>
                 </span>

                  <span>
                        <%=text_area_tag "imodec_topic[pages][]","",:class=>"span6 page-area",:rows => "5"%>
                        <%=link_to "X","#",:class=>"delete-page"%>
                 </span>
              
                  <div>
                  <%=link_to "+添加内页","#",:id=>"add_page" unless @topic.body.present?%>
                  </div>
               </div>
        <%end%>

        
      </div>
    </div>
    <div class="control-group">
      <%= f.label :summary, "摘要", :class => "control-label" %>
      <div class="controls">
        <%= f.text_area :summary, :class => "span6", :rows => "5" %>
      </div>
    </div>
    <div class="control-group">
       <%= f.label :cover, "封面", :class => "control-label" %>
       <div class="controls">
          <%= f.select :cover_size, Imodec::Topic::COVER_SIZES, {}, :class => "span2" %>
          <%= f.file_field :cover %><br/><br/>
          <% if @topic.cover.file? %>
          <%= image_tag @topic.cover.url(@topic.cover_size) %><br/><br/>
          <label class="checkbox" for="imodec_topic_remove_cover">
            <%= f.check_box :remove_cover %>删除封面
          </label>
          <% end %>
       </div>
    </div>
    <div class="control-group">
      <label class="control-label">设定</label>
      <div class="controls">
        <label class="checkbox" for="imodec_topic_published">
          <%= f.check_box :published %>立刻发布
        </label>
      </div>
    </div>

     <div class="control-group">
      <label class="control-label">访问设置</label>
      <div class="controls">
        <label class="checkbox" for="imodec_topic_require_login">
          <%= f.check_box :require_login %> 登录
        </label>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">评论设置</label>
      <div class="controls">
        <label class="checkbox" for="imodec_topic_commentable">
          <%= f.check_box :commentable %> 开启评论
        </label>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :page_keywords, "关键字", :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :page_keywords, :placeholder => "网页关键字,提示：逗号分割",:class=>"span5" %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :page_description, "网页描述", :class => "control-label" %>
      <div class="controls">
        <%= f.text_field :page_description, :placeholder => "网页描述",:class=>"span5" %>
      </div>
    </div>


    <div class="control-group">
      <div class="controls">
        <%= f.submit '确定', :class => "btn btn-primary" %>&nbsp;&nbsp;&nbsp;&nbsp;<%= link_to '返回', admin_topics_path %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/admin/topics/edit.html.erb
<h1>编辑专题</h1>

<%= render 'form' %>

app/views/admin/topics/index.html.erb
<div class="page-header">
  <h2>所有专题
    <%= link_to '新建专题', new_admin_topic_path, :class => "pull-right btn btn-primary" %>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <%= link_to '添加分类', "javascript:void(0);", :class => "pull-right btn btn-primary dialog", :'data-url'=>admin_categories_path,:style=>"margin-right:10px;" %>
  </h2>

</div>

<table class="table table-bordered table-hover">
  <tr>
    <th>分类</th>
    <th>专题标题</th>
    <th>发布时间</th>
    <th>是否发布</th>
    <th>是否登录访问</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.category.name if topic.category %></td>
    <td><%= topic.title %></td>
    <td>
      <%if topic.published%>
        <span class="time-holder" data-time='<%=topic.published_at.strftime("%Y-%m-%d %H:%M:%S")%>'>
          <%=topic.published_at.strftime("%Y-%m-%d %H:%M:%S")%>
        </span>
        <%=link_to "#",:title=>"修改发布时间",:class=>"edit-time",:'data-url'=>published_at_admin_topic_path(topic),:remote=>true do %>
          <i class="icon-edit" title="修改发布时间"></i>
        <%end%>
      <%else%>
        草稿
      <%end%>
    </td>
    <td><%= topic.published ? '是' : '否' %></td>
    <td><%= topic.require_login ? '是' : '否' %></td>
    <td><%= link_to '查看', topic_path(topic) %></td>
    <td><%= link_to '编辑', edit_admin_topic_path(topic) %></td>
    <td><%= link_to '删除', admin_topic_path(topic), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<div class="pagination">
  <%= will_paginate @topics, :container => false %>
</div>

app/views/admin/topics/new.html.erb
<div class="page-header">
  <h2>新建专题</h2>
</div>

<%= render 'form' %>