config/routes.rb
require 'httpclient'
Modengke::Application.routes.draw do

 get 'articles/gyyx/gswh' => 'articles/gyyx#gswh'
 get 'articles/gyyx/gsgs' => 'articles/gyyx#gsgs'
 get 'articles/shzr/bzsy' => 'articles/shzr#bzsy'
 get 'articles/shzr/spaq' => 'articles/shzr#spaq'
 get 'articles/hzgy/hwys' => 'articles/hzgy#hwys'
 get 'articles/lxwm/zgzb' => 'articles/lxwm#zgzb'
 get 'articles/xwcx/xwdt' => 'articles/xwcx#xwdt'
 get 'articles/xwcx/xwdt/:id' => 'articles/xwcx#show'

 resources :contacts

 resources :cases

 resources :commissions do
  collection do
   get  'platform'
   get 'bank_info'
 end

 member do
  get 'paid'
end
end

mount WeixinRailsMiddleware::Engine, at: "/"

root :to=>"home#index",:constraints=>{ :subdomain=>/^(www)?$/ }
get 'blank'=>"home#blank"
get 'home'=>"home#index"

resources :pages, :only=>[:show]

namespace :auth do
  resources :accounts
  resources :weixin do
    get 'callback',:on=>:member
  end
  resources :weibo do
    get 'callback',:on=>:collection
  end
  resources :douban do
    get 'callback',:on=>:collection
  end
end

resources :sessions

get 'register'=>'users#new'
resources :users do
  get 'forgot_password', :on=>:collection
  post 'send_reset_password_instruction', :on=>:collection    
  get 'reset_password',:on=>:collection
  post 'search', :on=>:collection
  post 'change_password',:on=>:collection
  post 'update' ,:on=>:member
end

resources :vshop do
  collection do
    get 'login'
    get 'register'
    get 'article'
    get 'apply'
    post 'search'
    post 'change_password'
    get 'goods'
    get 'orders'
    get 'members'
    get 'weixin'
    post "destory"
  end
  member do
    get :user
    get :category
    get :commodity
    get :order
     get :payments
     get :native
     post :paynotifyurl
     get :paynotifyurl
     get :feedback
   end
 end

 get 'auto_login'=>"sessions#auto_login"
 get 'login'=>"sessions#login"
 get 'mlogin'=>"sessions#new_mobile"
 get 'mregister'=>"sessions#register_mobile"
 post 'login'=>"sessions#create"
 post 'mlogin'=>"sessions#create"
 get 'logout'=>"sessions#destroy"
 get 'topmenu'=>"home#topmenu"

 scope :module=> "events" do
  resources :user_survey, :controller=>"survey" do
    post "add_mobile", :on=>:collection
  end
end

namespace :events do
  resources :applicants
end

resources :events

scope :module => "blog" do
    root :to => "articles#index"
    resources :articles

  end

  scope :module => "magazine" do
    resources :topics do
      resources :pages
    end
    match '/more_topics' => 'topics#more'
    match '/list_topics' => 'topics#list'
    match '/flash' => 'flashes#index'
  end

  scope :module => "memberships" do
    match '/vip' => 'vip#index'
    resource  :card do
      collection do
        get 'search'

        get 'activation'
        post 'confirm_activation'
        post 'validate_activation'
        post 'activate'
        get 'complete_activation'
        post 'input_mobile'
        post 'select'
        put 'update_mobile'
        put 'modify_mobile'
        get 'cancel_mobile'

        get 'purchase'
        scope "purchase" do
          post 'confirm_buyer'
          post 'confirm_user'
          get 'user'
        end

        get 'send_sms_code'

      end
    end
    resources  :member_cards
  end

  get 'admin'=>'admin/sessions#new'

  namespace :admin do

    get 'logout'=>'sessions#destroy'
    resources :tracks do
      get :pages,:on=>:collection
    end

    resources :discount_codes

    resources :carts do

    end
    resources :wechat do
      get :menu,:on=>:collection
      get :menu_edit,:on=>:collection
      get :followers, :on=>:collection
      get :followers_import, :on=>:collection
      get :follower_renew,:on=> :collection
      get :groups, :on=>:collection
      get :batch_sending, :on=>:collection
      get :weixin,:on=>:collection
    end
    resources :resources
    resources :permissions do
    end
    get 'permissions/:id/role' => 'permissions#role', as: :permission_role

    resources :suppliers do
      get 'update_state',:on=>:collection
    end

    resources :sessions
    resources :coupons
    resources :goods_cats do
      get :create_top,:on=>:collection
      get :toggle_future,:on=>:member
      get :toggle_agent,:on=>:member
      get :toggle_sell,:on=>:member
      post :save_top,:on=>:collection
    end
    resources :goods_types do
      put :updateType,:on=>:member
    end
    resources :goods_labels do
      put :updateLabel,:on=>:member
      get :createLabel,:on=>:collection
    end

    resources :brand_adms do
      get :delete
      put :update_brand,:on=>:member
    end

    resources :goods do
      post "export", :on=>:collection
      post "import", :on=>:collection
      post "remove_spec_item",:on=>:member
      get "add_spec_item",:on=>:member
      get "spec",:on=>:member
      put "update_spec",:on=>:member
      get 'select_goods',:on=>:collection
      get 'collocation',:on=>:member
      get 'set_suits',:on=>:member
      get 'cancel_suits',:on=>:member
      post 'create_collocation',:on=>:collection
      get 'search', :on=>:collection
      get 'select_gifts',:on=>:collection
      put 'batch',:on=>:collection
      get 'select_all',:on=>:collection

      get :toggle_future,:on=>:member
      get :toggle_agent,:on=>:member
      get :toggle_sell,:on=>:member
    end
    resources :spec_items

    resources :images do
      post "mark", :on=>:collection
      post "rollback",:on=>:collection
      post "refresh",:on=>:collection
    end
    resources :articles do
      post 'set_position',:on=>:collection
    end
    resources :topics do
      post 'set_position',:on=>:collection
      post 'published_at',:on=>:member
    end
    resources :pages

    resources :members do
      post "export",:on=>:collection
      post "column_reload",:on=>:collection
      post "send_sms",:on=>:collection
      post "send_sms2",:on=>:collection
      get :info,:on=>:member
      put :updateInfo,:on=>:member
    end

    resources :cards do
      get 'buy',:on=>:member
      get 'use',:on=>:member
      get 'edit_user',:on=>:member
      get 'edit_pay',:on=>:member
      get 'logs', :on=>:member
      post 'import', :on=>:collection
      post "export",:on=>:collection
      get "tag",:on=>:collection
      put "untag",:on=>:member
      put "cancel_order",:on=>:member
    end

    resources :users do
      get 'search',:on=>:collection
      post 'newuser',:on=>:collection
      put 'send_sms_code',:on=>:member
      put 'buy_card',:on=>:member
      put 'use_card',:on=>:collection
      get 'select', :on=>:member
      put 'validate_mobile',:on=>:member
    end
    resources :member_cards

    resources :tag_exts

    resources :configs

    resources :labels

    resources :emails do
      get 'send_all',:on=>:collection
    end

    resources :categories

    resources :applicants

    resources :events do
      get 'applicants',:on=>:member
    end

    resources :homes

    resources :brand_pages do
      get 'toggle', :on=>:member
      put 'order', :on=>:member
      put 'reco', :on=>:member
    end

    resources :promotions

    resources :new_coupons do
      get 'download', :on=>:member
      get  'select_coupons', :on=>:collection
    end

    resources :user_coupons

    resources :orders do
      collection do
        get 'search'
        post :export
        put 'batch'
      end

      member do
        get 'detail'
        get 'pay'
        post 'dopay'
        get 'delivery'
        post 'dodelivery'
        get 'print_order'
        get 'print_preparer'
        get 'reship'
        post 'doreship'
        get 'refund'
        post 'dorefund'
        get :comment
        put :update_memo
      end
    end

    resources :static_pages
    resources :footers

    resources :metas

    resources :specifications

    resources :tags

    resources :offline_coupons do
      get 'downloads',:on=>:member
    end

    resources :virtual_goods do
      post 'import', :on=>:collection
    end

    resources :payment_logs

  end
  get 'm' =>"mobile#show", :as=>"mobile" ,:controller=>"mobile"

  scope :module => "store" do

    get 'search' => "search#index", :as=> :search
    get 'mproducts' =>"goods#mproduct", :as=>"goods" ,:controller=>"goods"

    resources :products, :as=>"goods", :controller=>"goods" do
      get 'newest',:on=>:collection
      put 'fav',:on=>:member
      put 'unfav',:on=>:member
      get 'price',:on=>:member
      get 'more',:on=>:collection
      get 'suits', :on=>:collection
      get 'more_suits', :on=>:collection

    end

    resources :suppliers

    resources :coupons, :controller=>"offline_coupons" do
      post 'download',:on=>:member
    end

    resources :vgoods, :controller=>"virtual_goods",:only=>[:index,:show]
    post 'cart/add'=>"cart#add",:as=>:add_to_cart

    resources :cart do
      get 'manco_express'  ,:on=>:collection
      get 'distribution_manco',:on=>:collection
      post 'add',:on=>:collection
      get 'mobile', :on=>:collection
    end
    resources :brands,:only=>[:index,:show]
    resources :users
    resources :vshop
    resources :country, :as=>"countries", :controller=>"countries"
    resources :gallery, :as=>"cats", :controller=>"cats"

    get 'mgallery' =>"cats#show_mobile", :as=>"cats",:controller=>"cats"
    get 'mgoods_list'=>"cats#goods_list" ,:as=>"cats", :controller=>"cats"
    resources :goods,  :as=>"orders", :controller=>"orders" do
      member do
        get :goods
      end
    end

    get 'share' =>"orders#share"

    resources :orders, :except=>[:index] do
      member do
        get 'to_inventory'
        get 'out_inventory'
        post :pay
        get :detail
        get :goods

      end

      collection do
        post 'destroyaddr'
        get 'check_coupon'
        get  'new_mobile'
        get  'new_tairyo'

        post 'new_manco'
        get 'new_mobile_addr'
        get 'new_manco_addr'
        get 'departure'
        post 'arrival'
        get 'arrival'

app/models/ecstore/new_coupon.rb
#encoding:utf-8
require 'securerandom'
require 'digest'

class Ecstore::NewCoupon < Ecstore::Base
	self.table_name = "sdb_imodec_coupons"
	self.accessible_all_columns

	attr_accessor :current_code

	validates :coupon_prefix, uniqueness: { message: "优惠券号码不能重复" }
	validates_presence_of :name,:message=>"名称不能为空"
	validates_presence_of :desc,:message=>"描述不能为空"

	before_create :set_coupon_key

	def set_coupon_key
		self.coupon_key = SecureRandom.base64(10)
	end

	# before_save :set_coupon_prefix

	# def set_coupon_prefix
	# 	self.coupon_prefix = self.coupon_type + self.coupon_prefix
	# end

	def prefix
		return nil if self.coupon_prefix.blank?
		self.coupon_prefix[1..-1]
	end


	def enable?
	      return false  unless  self.enable
	  	now =  Time.now
	       if self.begin_at.blank? && self.end_at.blank?
	          return true
	       end
	       if self.begin_at.blank? && self.end_at.present?
	           return self.end_at >= now
	       end
	       if self.begin_at.present? && self.end_at.blank?
	          return self.begin_at <= now
	       end
	       return (self.begin_at <= now&& self.end_at >= now)
	end

	def condition_val=(v)
		super(v.to_s)
	end

	def condition_val
		return eval(super)  if super.present?
		nil
	end


	def generate_coupon_code(update_quantity=false)

		return self.coupon_prefix if self.coupon_type == "A"

		no = self.quantity + 1

		key = self.coupon_key
		prefix = self.coupon_prefix
		no = no.to_s(36)
		no = "0" * ( 5 - no.size ) + no
		part = Digest::MD5.hexdigest("#{key}#{no}#{prefix}")[0..4]
		code = "#{prefix}#{part.upcase}#{no.upcase}"
		self.increment!(:quantity) if update_quantity

		code
	end

	def self.check_code(code)
		return false  if code.blank?
		_type = code[0].upcase

		if _type == "A"
			_coupon = self.find_by_coupon_prefix(code)
			return _coupon.present?
		end

		if _type == "B"
			return false if code.size < 11

			_prefix = code[0..-11]
			_coupon = self.find_by_coupon_prefix(_prefix)
			return false  if _coupon.blank?
			
			_no = code[-5..-1].downcase

			_part = Digest::MD5.hexdigest("#{_coupon.coupon_key}#{_no}#{_coupon.coupon_prefix}")[0..4]
			check_code = "#{_coupon.coupon_prefix}#{_part.upcase}#{_no.upcase}"
			return check_code == code.upcase
		end

		false
	end

	def self.check_and_find_by_code(code)

		return nil  unless self.check_code(code)
		_type = code[0].upcase
		if _type == "A"
			_coupon =  self.find_by_coupon_prefix(code)
			_coupon.current_code = code
			return _coupon
		end

		if _type == "B"
			_coupon =  self.find_by_coupon_prefix(code[0..-11])
			_coupon.current_code = code
			return _coupon
		end
	end

	
	def test_condition(line_items = [])
		order_amount  = line_items.collect { |line| line.product.price * line.quantity }.inject(:+).to_i

		cart_goods = line_items.collect { |line| line.good.bn }

		if condition_type == 'order_total_ge_x'
			return true  if order_amount > condition_val
		end

		if condition_type == 'buy_specify_goods'
			return (cart_goods & condition_val).present?
		end
		false
	end


	def pmt_amount(line_items = [])
		return self.action_val.to_i if self.action_type == "order_minus"

		order_amount  = line_items.collect { |line| line.product.price * line.quantity }.inject(:+).to_i
		return order_amount - (order_amount*self.action_val.to_i / 100).round  if self.action_type == "order_discount"
		0 
	end

end

app/controllers/admin/new_coupons_controller.rb
require 'csv'

class Admin::NewCouponsController < Admin::BaseController

	def index
		@coupons = Ecstore::NewCoupon.paginate(:per_page=>10,:page=>params[:page],:order=>"created_at asc")
	end

	def new
		@coupon  = Ecstore::NewCoupon.new
		@action_url = admin_new_coupons_path
		@method = :post
	end

	def show
		@coupon  = Ecstore::NewCoupon.find(params[:id])
	end

	def edit
		@coupon  = Ecstore::NewCoupon.find(params[:id])
		@action_url = admin_new_coupon_path(@coupon)
		@method = :put
	end

	def create
		params[:coupon][:coupon_prefix] = params[:coupon][:coupon_type] + params[:coupon][:coupon_prefix] 
		@coupon  = Ecstore::NewCoupon.new(params[:coupon])

		if @coupon.save
			redirect_to admin_new_coupons_url
		else
			render :new
		end
	end

	def update
		params[:coupon][:coupon_prefix] = params[:coupon][:coupon_type] + params[:coupon][:coupon_prefix] 
		@coupon  = Ecstore::NewCoupon.find(params[:id])
		if @coupon.update_attributes(params[:coupon])
			redirect_to admin_new_coupons_url
		else
			render :edit
		end
	end

	def destroy
		@coupon  = Ecstore::NewCoupon.find(params[:id])
		@coupon.destroy

		redirect_to admin_new_coupons_url
	end


	def download
		@coupon =  Ecstore::NewCoupon.find(params[:id])
		count = (params[:count] || 50).to_i

		file_name = "coupons_#{Time.now.to_i}.csv"
		download_file = "#{Rails.root}/public/tmp/#{file_name}"

		CSV.open(download_file,"wb") do |csv|
			count.times do
				csv << [@coupon.generate_coupon_code(true)]
			end
		end

		render :text => "/tmp/#{file_name}"
	end

	def select_coupons

		@coupons = Ecstore::NewCoupon.paginate(:per_page=>20,:page=>params[:page])
		
		respond_to do |format|
	            format.html { render :layout=> "dialog" }
	            format.js
	      end
	end
	
end

app/helpers/admin/new_coupons_helper.rb
module Admin::NewCouponsHelper
end

app/views/admin/new_coupons/_coupons.html.erb
<%@coupons.each do |coupon|%>
          <tr data-page="<%=params[:page] || 1%>">
              <td><%=check_box_tag "id", coupon.id, false, {:'data-name'=>"#{coupon.name}"}%></td>
              <td><%=coupon.name%></td>
              <td><%=coupon.enable?  ? "是" : "否"%></td>
              <td><%=coupon.quantity%></td>
              <td><%=coupon.coupon_type%></td>
           </tr>  
<%end%>

app/views/admin/new_coupons/_form.html.erb
<%if @coupon.errors.size > 0%>
<div class="alert error">提交失败，请检查数据正确性</div>
<%end%>

<%=form_for :coupon,:url=>@action_url,:method=>@method,:html=>{:class=>"form-horizontal"} do |f|%>

<div class="control-group">
    <%=f.label :name, "名称*",:class=>"control-label"%>
    <div class="controls">
      <%=f.text_field :name%>
      <span class="help-inline error"><%=@coupon.errors[:name].join(",")%></span>
    </div>
</div>

<div class="control-group">
    <%=f.label :desc, "描述*",:class=>"control-label"%>
    <div class="controls">
      <%=f.text_area :desc,:rows=>3%>
      <span class="help-inline error"><%=@coupon.errors[:desc].join(",")%></span>
    </div>
</div>


<div class="control-group">
    <%=f.label :name, "是否开启*",:class=>"control-label"%>
    <div class="controls">
      <label class="radio inline">
      <%=f.radio_button :enable,true,:checked=>true%> <span>是</span>
      </label>
      <label class="radio inline">
      <%=f.radio_button :enable,false%> <span>否</span>
      </label>
    </div>
</div>

<div class="control-group">
    <%=f.label :priority, "优先级",:class=>"control-label"%>
    <div class="controls">
      <%=f.text_field :priority,:class=>"span2",:placeholder=>"数字越大优先级越高"%>
    </div>
</div>
<div class="control-group">
    <%=f.label :exclusive, "是否排它*",:class=>"control-label"%>

    <div class="controls">
      <label class="radio inline">
      <%=f.radio_button :exclusive,true,:checked=>true%> <span>是</span>
      </label>
      <label class="radio inline">
      <%=f.radio_button :exclusive,false%> <span>否</span>
      </label>
       
    </div>

</div>

<div class="control-group">
    <label class="control-label">开始时间</label>
    <div class="controls">
      <%=f.text_field :begin_at,:value=>@coupon.begin_at&&@coupon.begin_at.strftime("%Y-%m-%d %H:%M:%S"),:class=>"span2 datetime"%>
    </div>
</div>

<div class="control-group">
    <label class="control-label">结束时间</label>
    <div class="controls">
      <%=f.text_field :end_at,:value=>@coupon.end_at&&@coupon.end_at.strftime("%Y-%m-%d %H:%M:%S"),:class=>"span2 datetime"%>
    </div>
</div>


<div class="control-group">
    <%=f.label :coupon_type, "类型*",:class=>"control-label"%>
    <div class="controls" id="toggle_coupon_type">
      <label class="radio">
          <%=f.radio_button :coupon_type,"A",:checked=>true%>
          <span>A类优惠券</span>
          <span class="help-inline">
            只需获得一张，即可在规定的时间内重复使用
          </span>
      </label>

      <label class="radio">
          <%=f.radio_button :coupon_type,"B"%>
          <span>B类优惠券</span>
          <span class="help-inline">
            可一次获得多张，但在规定时间内每张只能使用一次，无法重复使用
          </span>
      </label>
    </div>
</div>

<div class="control-group">
    <%=f.label :coupon_prefix, "号码*",:class=>"control-label"%>
    <div class="controls">
      <span id="static_coupon_type"><%=@coupon.coupon_type ? @coupon.coupon_type : "A"%></span>
      <%=f.text_field :coupon_prefix,:value=>@coupon.prefix,:class=>"span2",:readonly=>!@coupon.new_record?%>
      <span class="help-inline error"><%=@coupon.errors[:coupon_prefix].join(",")%></span>
    </div>

</div>



<div class="control-group">
    <label class="control-label">使用条件</label>
    <div class="controls" id="conditions">
       <label class="radio">
          <%=f.radio_button :condition_type,"order_total_ge_x"%><span>订单金额满X元</span>
      </label>
      <label class="radio">
          <%=f.radio_button :condition_type,"buy_specify_goods"%><span>购买指定商品</span>
      </label>

       <div class="help-block alert">
          <span id="condition_val">
            <%=link_to "+选择商品","#" if @coupon.condition_type == 'buy_specify_goods'%>
            <%if @coupon.condition_type == 'order_total_ge_x'%>
              输入 X = <%=f.text_field :condition_val,:class=>"input-mini"%>
            <%end%>
          </span>
         <ul id="selected_goods" class="goods-list">
          <%@coupon.condition_val.each do |bn|%>
            <% good =  Ecstore::Good.find_by_bn(bn)%>
            <li><%=good.name%> <%=bn%></li>
          <%end if @coupon.condition_val.is_a?(Array)%>
         </ul>
       </div>
    </div>
</div>

<div class="control-group">
    <label class="control-label">使用方案</label>
    <div class="controls" id="actions">
       <label class="radio">
          <%=f.radio_button :action_type,"order_minus",:checked=>true%><span>订单减去Y元出售</span>
      </label>
      <label class="radio">
          <%=f.radio_button :action_type,"order_discount"%>
          <span>订单Y(0~100)折扣出售 (如:八折 Y=80)</span>
      </label>

      <div class="help-block alert">
          <span id="action_val">
              输入 Y = <%=f.text_field :action_val,:class=>"input-mini"%>
          </span>
       </div>

    </div>
</div>



<div class="control-group">
    <div class="controls">
      <%=f.submit "提 交",:class=>"btn btn-primary"%>
      <%=link_to "取消",admin_new_coupons_path,:class=>"btn"%>
    </div>
</div>
<%end%>



<script type="text/javascript">
    $(document).ready(function(){
        $("#condition_val").on('click','a',function(){
            window.open('/admin/goods/select_goods?goods_type=normal&target=selected_goods&field_name=condition_val&model_name=coupon', 'newwindow', 'height=500, width=750, top=400, left=600, toolbar=no, menubar=no, scrollbars=no,resizable=yes,location=no, status=no');
        });
    });
</script>

app/views/admin/new_coupons/edit.html.erb
<h3>编辑优惠券</h3>
<%=render "form"%>

app/views/admin/new_coupons/index.html.erb
<h4>
  优惠券
</h4>
<hr>

<h1>
  <%=link_to "添加优惠券",new_admin_new_coupon_path,:class=>"btn btn-primary right"%>
</h1>

<table class="table table-bordered table-hover">
    <tr>
      <th>名称</th>
      <th>类型</th>
      <th>开启状态</th>
      <th>是否排它</th>
      <th>有效期</th>
      <th>优先级</th>
      <th>数量</th>
      <td>优惠券号码</td>
      <th>操作</th>
    </tr>
    
  <%@coupons.each do |coupon|%>
    <tr class="<%= 'disable' unless coupon.enable?%>">
      <td><%=coupon.name%></td>
      <td><%=coupon.coupon_type%></td>
      <td><%=coupon.enable ? "是" : "否"%></td>
      <td><%=coupon.exclusive ? "是" : "否"%></td>
      <td><%=coupon.begin_at.strftime("%Y-%m-%d %H:%M:%S") if coupon.begin_at.present?%> ~ <%=coupon.end_at.strftime("%Y-%m-%d %H:%M:%S") if coupon.end_at.present?%></td>
      <td><%=coupon.priority%></td>
      <td><%=coupon.quantity%></td>
      <td><%=coupon.coupon_prefix%></td>
      <td>
        <%=link_to "编辑", edit_admin_new_coupon_path(coupon)%>
        
        <%=link_to "删除", admin_new_coupon_path(coupon),:method=>:delete,:confirm=>"确定要删除？"%>


        <%=link_to "下载", download_admin_new_coupon_path(coupon),:class=>"download" if coupon.coupon_type=="B" && coupon.enable? %>
      </td>
    </tr>
    <%end%>
  </table>

  <div class="pagination">
    <%=will_paginate @coupons,:container=>false%>
  </div>

app/views/admin/new_coupons/new.html.erb
<h3>新建优惠券</h3>

<%=render "form"%>

app/views/admin/new_coupons/select_coupons.html.erb
<div id="dialog_goods">

<div>已经选中<b id="selected_count">0</b>条</div>
<table class="table table-bordered table-hover" id="select_coupons">
          <tr class="header">
            <th><%=check_box_tag "select_all",1%></th>
            <th>优惠券名称</th>
            <th>是否启用</th>
            <th>获取总数量</th>
            <th>优惠券类型</th>
          </tr>
        <%=render "coupons"%>
</table>

<div class="pagination">
  <%=will_paginate @coupons,:container=>false%>
</div>

<div>
  <%=link_to "确 定","#",:class=>"btn btn-primary",:id=>"confirm_select"%>
</div>
<br>
<script>
  $(document).ready(function(){
    
    var counterSelect = function(){
        var counter = $("#select_coupons input[name='id']:checked").length;
        $("#selected_count").text(counter)
    };

    $("#select_coupons").on("change","#select_all",function(){
        if($(this).attr("checked") == "checked"){
           $("#select_coupons input[name='id']").attr("checked",true)
           $("#select_coupons input[name='id']").closest("tr").addClass("checked");
        }else{
          $("#select_coupons input[name='id']").attr("checked",false)
          $("#select_coupons input[name='id']").closest("tr").removeClass("checked");
        }
        counterSelect();
    });
    $("#select_coupons").on("change","input[name='id']",function(event,checked){

        if($(this).attr("checked")=="checked"){
            $(this).attr("checked",true);
            $(this).closest("tr").addClass("checked");
        }else{
            $(this).attr("checked",false);
            $(this).closest("tr").removeClass("checked");
        }
        counterSelect();
    });

   var opener = window.opener.document;
    var target = '#<%=params[:target]%>';
    var fieldName = "<%=params[:field_name] || 'action_val'%>";
    var modelName = "<%=params[:model_name] || 'promotion'%>"
    $("#confirm_select").click(function() {
          $(opener).find(target).empty();
          $("#select_coupons input[name='id']:checked").each(function() {
            var hidden_input, html_bn;
            html_bn = $(this).data('name');
            hidden_input = "<input name='"+modelName+"["+fieldName+"][]' type='hidden' value='" + ($(this).val()) + "' >";
            $(opener).find(target).append("<li>" + html_bn + hidden_input + "</li>");
          });
          window.close();
          return false;
    });
    
    var selectedGoods = []

    $(opener).find(target).find("input:hidden").each(function(){
             selectedGoods.push($(this).val());
            // $("input[value='"+$(this).val()+"']").attr("checked",true).trigger("change");
    });



    var doSelect = function(){
       var dels = []
        for(var i in selectedGoods){
           var bn = selectedGoods[i];
           if( $("input[value='"+bn+"']").length>0 ){
              $("input[value='"+bn+"']").attr("checked",true).trigger("change");
              dels.push(i)
           } 
        }
        for(var d in dels){
          selectedGoods.splice(dels[d],1);
        }
    };
    doSelect()
    
    $("#selected_count").text($(opener).find(target).find("input:hidden").length);

    $("#dialog_goods .pagination").on('click', 'a', function() {
      var url;
      url = $(this).attr("href");
      $.getScript(url,function(){
        doSelect();
      });
      return false;
    });

  });
</script>
</div>